services:
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  producer:
    build:
      context: ./producer
    volumes:
      - ./producer:/app
    working_dir: /app
    command: ["python", "kafka_producer.py"]
    depends_on:
      - kafka
      - mongodb

  consumer:
    build:
      context: ./consumer
    volumes:
      - ./consumer:/app
    working_dir: /app
    command: ["python", "kafka_consumer.py"]
    depends_on:
      - kafka
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db


  spark-master:
    build:
      context: ./spark
    container_name: spark-master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-src.zip
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./flask_app:/app

  spark-worker: 
    build:
      context: ./spark
    container_name: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-src.zip
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./flask_app:/app

  spark-job:
    build:
      context: ./spark
      dockerfile: Dockerfile_sj
    command: ["/opt/spark/bin/spark-submit", "--master", "spark://spark-master:7077", "--jars", "/opt/spark/jars/connettore.jar", "/app/spark_job_batch.py"]
    depends_on:
      - spark-master
      - mongodb
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./spark:/app

  flask-app:
    build:
      context: ./flask-app
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - FLASK_APP=PROJECT.py
    ports:
      - "5000:5000"
    depends_on:
      - spark-master
      - mongodb
    volumes:
      - ./flask-app:/app